# auto generate by generator
build:
	go mod tidy
	go build .
	@echo "Build successfully"
docker:
	go mod tidy
	GOOS=linux GOARCH=amd64 go build -o dist/{{.ProjectName}} .	
	docker build -t {{.ProjectName}}-img -f Dockerfile .
dockerremove:
	docker rm {{.ProjectName}}
	docker rmi {{.ProjectName}}-img
dockerrun:	
	docker run -p {{.ListenPort}}:{{.ListenPort}} --name {{.ProjectName}} -e GIN_MODE=release --net devnetwork {{.ProjectName}}-img
dockershell:
	docker run -it -p {{.ListenPort}}:{{.ListenPort}} --name eventapi -e GIN_MODE=release  --entrypoint=/bin/sh --net devnetwork {{.ProjectName}}-img
apitest:
	go get -t ./test
	grc go test -v ./test/*.go
windows:
	go get .
	GOOS=windows GOARCH=amd64 go build -o dist/{{.ProjectName}}-win.exe .
linux:
	go get .
	GOOS=linux GOARCH=amd64 go build -o dist/{{.ProjectName}}-linux.bin .
mac:
	go get .
	GOOS=darwin GOARCH=amd64 go build -o dist/{{.ProjectName}}-mac.bin .